repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=auto]
      - id: trailing-whitespace
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff
        language: system
        require_serial: true
        types: [python]
        stages: [pre-commit]
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        require_serial: true
        types: [python]
        stages: [pre-commit]
      - id: pytest
        name: pytest, all tests
        entry: pytest tests/
        args: [--all-files]
        language: system
        stages: [pre-push]
